services:
  mysql:
    image: mysql:latest
    container_name: womsec-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin
      MYSQL_DATABASE: wosec
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
